In [7]:
import numpy as np
import pandas as pd
print("All of the libraries are imported successfully.")

All of the libraries are imported successfully.

In [6]:
marks= np.array([90, 80, 70, 60, 50])
print("Marks:", marks)
print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Standard Deviation:", np.std(marks))
print("Max:", np.max(marks))
print("Min:", np.min(marks))
print("Median:", np.median(marks))

Marks: [90 80 70 60 50]
Sum: 350
Mean: 70.0
Standard Deviation: 14.142135623730951
Max: 90
Min: 50
Median: 70.0

In [10]:
df= pd.read_csv("../titanic.csv")
print("CSV File loaded successfully.")

CSV File loaded successfully.

In [11]:
import os
print(os.getcwd())

/workspaces/python-to-ai-bootcamp/day-2/Day2Practice

In [ ]:
print("Printing first 3 rows of the DataFrame:")
display(df.head(3))
print("Last 2 rows of the DataFrame:")
display(df.tail(2))

Printing first 3 rows of the DataFrame:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

Last 2 rows of the DataFrame:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [20]:
print("Dataset Shape:", df.shape)
print("\n Column names:", df.columns)
print("\n Dataset Info:")
df.info()
print("\n Dataset Description:", df.describe())

Dataset Shape: (891, 12)

 Column names: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

 Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

 Dataset Description:        PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [21]:
print("Missing values in each column:")
 
display(df.isnull().sum())

Missing values in each column:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
selected_data = df.loc[
    :, ["Name", "Survived", "Age", "Parch", "Cabin"]
]
 
display(selected_data.head())

,Name,Survived,Age,Parch,Cabin
0,"Braund, Mr. Owen Harris",0,22.0,0,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,0,C85
2,"Heikkinen, Miss. Laina",1,26.0,0,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,0,C123
4,"Allen, Mr. William Henry",0,35.0,0,NaN

In [23]:
female_passengers = df.loc[
    df["Sex"] == "male",
    ["Name", "Age", "Survived"]
]
 
display(female_passengers.head(10))

                              Name   Age  Survived
0          Braund, Mr. Owen Harris  22.0         0
4         Allen, Mr. William Henry  35.0         0
5                 Moran, Mr. James   NaN         0
6          McCarthy, Mr. Timothy J  54.0         0
7   Palsson, Master. Gosta Leonard   2.0         0
12  Saundercock, Mr. William Henry  20.0         0
13     Andersson, Mr. Anders Johan  39.0         0
16            Rice, Master. Eugene   2.0         0
17    Williams, Mr. Charles Eugene   NaN         1
20            Fynney, Mr. Joseph J  35.0         0

In [25]:
first_five_rows = df.iloc[0:6, 0:5]
 
display(first_five_rows)

,PassengerId,Survived,Pclass,Name,Sex
0,1,0,3,"Braund, Mr. Owen Harris",male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
2,3,1,3,"Heikkinen, Miss. Laina",female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,5,0,3,"Allen, Mr. William Henry",male
5,6,0,3,"Moran, Mr. James",male

## How many passangers have survived?

In [26]:
print("Survival counts:")
 
display(df["Survived"].value_counts())
 
print("Survival percentages:")
 
display(
    df["Survived"].value_counts(normalize=True) * 100
)

Survival counts:

Survived
0    549
1    342
Name: count, dtype: int64

Survival percentages:

Survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

## How many males and females were there in the titanic? Calculating there percantage.

In [ ]:
print("No. of Passengers:")
display(df["Sex"].value_counts())
 
print("Percentage of genders present:")
 
display(
    df["Sex"].value_counts(normalize=True) * 100
)

No. of females present:

Sex
male      577
female    314
Name: count, dtype: int64

Percentage of genders present:

Sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

## How many passangers age was > than 50?

In [28]:
count = (df["Age"] > 50).sum()

print(count)

64

## Name of passangers of age>50:

In [29]:
print("Males older than 50:")
print(df[(df["Age"] > 50) & (df["Sex"] == "male")]["Name"])

print("\nFemales older than 50:")
print(df[(df["Age"] > 50) & (df["Sex"] == "female")]["Name"])

Males older than 50:
6                   McCarthy, Mr. Timothy J
33                    Wheadon, Mr. Edward H
54           Ostby, Mr. Engelhart Cornelius
94                        Coxon, Mr. Daniel
96                Goldschmidt, Mr. George B
116                    Connors, Mr. Patrick
124             White, Mr. Percival Wayland
150              Bateman, Rev. Robert James
152                        Meo, Mr. Alfonzo
155             Williams, Mr. Charles Duane
170               Van der hoef, Mr. Wyckoff
174                 Smith, Mr. James Clinch
222                 Green, Mr. George Henry
232               Sjostedt, Mr. Ernst Adolf
249           Carter, Rev. Ernest Courtenay
252               Stead, Mr. William Thomas
262                       Taussig, Mr. Emil
280                        Duane, Mr. Frank
317                    Moraweck, Dr. Ernest
326               Nysveen, Mr. Johan Hansen
406        Widegren, Mr. Carl/Charles Peter
438                       Fortune, Mr. Mark
449          Peuchen, Major. Arthur Godfrey
456               Millet, Mr. Francis Davis
467              Smart, Mr. John Montgomery
487                 Kent, Mr. Edward Austin
492              Molson, Mr. Harry Markland
493                 Artagaveytia, Mr. Ramon
545            Nicholson, Mr. Arthur Ernest
555                      Wright, Mr. George
570                      Harris, Mr. George
582              Downton, Mr. William James
587        Frolicher-Stehli, Mr. Maxmillian
625                   Sutton, Mr. Frederick
626          Kirkland, Rev. Charles Leonard
630    Barkworth, Mr. Algernon Henry Wilson
631             Lundahl, Mr. Johan Svensson
647     Simonius-Blumer, Col. Oberst Alfons
659              Newell, Mr. Arthur Webster
672             Mitchell, Mr. Henry Michael
684       Brown, Mr. Thomas William Solomon
694                         Weir, Col. John
695              Chapman, Mr. Charles Henry
714                   Greenberg, Mr. Samuel
745            Crosby, Capt. Edward Gifford
851                     Svensson, Mr. Johan
857                  Daly, Mr. Peter Denis
Name: Name, dtype: str

Females older than 50:
11                              Bonnell, Miss. Elizabeth
15                      Hewlett, Mrs. (Mary D Kingcome)
195                                 Lurette, Miss. Elise
268        Graham, Mrs. William Thompson (Edith Junkins)
275                    Andrews, Miss. Kornelia Theodosia
366     Warren, Mrs. Frank Manley (Anna Sophia Atkinson)
483                               Turkula, Mrs. (Hedwig)
496                       Eustis, Miss. Elizabeth Mussey
513       Rothschild, Mrs. Martin (Elizabeth L. Barrett)
571        Appleton, Mrs. Edward Dale (Charlotte Lamson)
591      Stephenson, Mrs. Walter Bertram (Martha Eustis)
765                 Hogeboom, Mrs. John C (Anna Andrews)
772                                    Mack, Mrs. (Mary)
774                Hocking, Mrs. Elizabeth (Eliza Needs)
820    Hays, Mrs. Charles Melville (Clara Jennings Gr...
829            Stone, Mrs. George Nelson (Martha Evelyn)
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
Name: Name, dtype: str